### PR TITLE
Update repos.yml

### PR DESCRIPTION
**Pull request by Suzuki-Re**
Added a bunch of repositories I collected but have nothing to do with

### CODE REVIEW

**Comment by Suzuki-Re** [comment]
Not sure why they failed
https://github.com/AntoineBalaine/perken-reaper-scripts
https://github.com/jamesWalker55/reaper-scripts
https://github.com/odedd/ReaScripts

**Comment by Suzuki-Re** [comment]
Sorry I didn't double check and batch converted URL. All should be good now

**Comment by Suzuki-Re** [comment]
@cfillion What do I need to do? Or should I stop submitting multiple repos all at once?

**Comment by cfillion** [comment]
(Thanks for the reminder) No it's fine, I just need to get around to check each of them then merge this.

**Comment by Suzuki-Re** [comment]
Thank you for the reply! I was just wondering if something is wrong, but I know it'll take a while to do it because it also takes time for me haha.

**Comment by Suzuki-Re** [comment]
Let's break them into manageable bite sized chunks

**Pull request closed without merging**
