### PR TITLE
update repo link wrb

### PR DESCRIPTION
**Pull request by bobobo-git**
hi
the original link is rerouted  (i contacted the author mklier but got no answer)
so i took the repo to my github and updated the link.
tested it , it seem to be ok as it is. 
it is not my repo but i consider it sad if it would be gone

greetings bobobo

### CODE REVIEW

**Comment by bobobo-git** [comment]
maybe you test the old link before updating my stuff

**Comment by cfillion** [comment]
What do you mean by rerouted? The existing URL seems to still be up.

**Comment by bobobo-git** [comment]
hi
i have been a little unclear
the link is ok. g
but the content of the index.xml has links to 
https://hartung.studioprojects/reaperwrb/dist/2.2.2/reaperwrb_2.html
f.i.
this will be rerouted to
https://hartung.studioprojects/reaperwrb/dist/2.2.2/reaperwrb_2.html
and fails there

**Comment by bobobo-git** [comment]
sorry. i failed here too :)
again
index.xml has links to
http://m-klier.de/projects/reaperwrb/dist/2.2.2/reaperwrb_2.html
and that will be reroutetd to 
https://hartung.studioprojects/reaperwrb/dist/2.2.2/reaperwrb_2.html
and won't find anything there

**Comment by cfillion** [comment]
It's nice to have made a fork to keep it available! Saw reaperblog's post on [this thread](https://forum.cockos.com/showthread.php?t=251090) and this notice in the project's README:

> ATTENTION: reapack support is probably going to be discontinued. Please do a manual install
from the .zip file available in the "release" folder.

...so I suppose it's reasonable to replace it with your fork.

**Comment by bobobo-git** [comment]
:)

**Pull request merged**
