### PR TITLE
New Repo

### PR DESCRIPTION
**Pull request by X-Raym**
X-Raym MIDI Makey Makey

### CODE REVIEW

**Comment by cfillion** [comment]
The url gives a 404 error: https://github.com/X-Raym/MIDI-Makey-MakeyrReadme should be https://github.com/X-Raym/MIDI-Makey-Makey#readme. I will merge this PR when it's fixed.

**Comment by X-Raym** [comment]
Oops, it should be good now.

**Comment by cfillion** [comment]
Thanks!

**Comment by X-Raym** [comment]
Thanks to you :smile:

**Pull request merged**
